app:
  build: .
  #env_file:
  #  - ./env.list
  ports:
    - 3080:3000
    - 8080:8080
  environment:
    NODE_ENV: development
    NODE_PORT: 3000
  volumes:
    - ./:/var/www
    - ../npm/:/npm
  #command: sleep infinity
  command: npm run dev
